### ISSUE TITLE
Autolabeler.yml Format

### ISSUE THREAD

**Issue by luisschubert** [probot/autolabeler#3]
What is the format used for the autolabeler.yml file?
What are the rules it could follow? (i'm not sure if this is implemented yet)

Edit:
So the rules for labels seem to be defined as patterns to be matched using ignore.
if a pattern matches a label is added to the issue.
@bkeepers

**Comment by luisschubert** [comment]
Loads the yaml file into content. not sure what format content is. assuming it is just base 64 file.
```
const content = await context.github.repos.getContent(context.repo({
      path: '.github/autolabeler.yml'
    }));
```
?`content.data.content` //why is it not just 'content'?

config file is loaded from yaml format into an iterable format. (array or object?)
```
const config = yaml.safeLoad(Buffer.from(content.data.content, 'base64').toString());
```

gets files?? what files are you getting for an issue? maybe it's a pullrequest issue?
```
const files = await context.github.pullRequests.getFiles(context.issue());
```

changedFiles contains the filenames of the files
```
const changedFiles = files.data.map(file => file.filename);
```

iterate over labels in config object
```
for (const label in config) {
   robot.log('looking for changes', label, config[label]);
```

creates new ignore matcher that contains the matchings defined in the config file
 ```
const matcher = ignore().add(config[label]);
```

find gets the first match of a file that matches the label //what if there are multiple files that need the label? doesn't find only match the first match in the array?
```
if (changedFiles.find(file => matcher.ignores(file))) {
        labels.add(label);
      }
    }
```


adds the labels to the issue
```
robot.log('Adding labels', labelsToAdd);
if (labelsToAdd.length > 0) 
  return context.github.issues.addLabels(context.issue({
    labels: labelsToAdd
  }));
}
```

**Comment by bkeepers** [comment]
Hey @luisschubert, thanks for your interest in this plugin. It's still a work in progress, so any feedback is appreciated!

In its current form, this plugin simply adds labels to pull requests based on the path of the files modified.

> What is the format used for the autolabeler.yml file?

It's a yaml file in the format of `label: file/path`.

```yml
frontend: ["*.js", "*.css", "*.html"]
backend: ["/app", "*.rb"]
legal: ["LICENSE*", "NOTICES*"]
config: .github
```

So if a pull request is opened that has `scripts/widget.js` modified, then the `frontend` label will be added.

Make sense?

**Comment by luisschubert** [comment]
Ah... thank you for clarifying that for me!
The plugin in its current form is labeling prs based on the types of files contained in it to determine what is relating to.

I'm looking to do something a little bit different...
The bot i'm wanting to build is supposed to help track progress on pull requests until they are either merged or closed. This plugin is definitely a good starting block. Still trying to understand how to best work with the github api.

**Comment by bkeepers** [comment]
@luisschubert that sounds really useful. Let me know if you have any questions or if you want someone to talk through ideas with.
