### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by aegershman** [probot/autolabeler#38]
EDIT: solved in comment below

Is it possible to publish this probot to npm?

## background
I'm trying to get this probot onto our corporate github enterprise. It would be much easier if this were published on `npm` so that I could bundle this entire app as a dependency within a single `package.json` and simply make that available as a `probot`.  E.g., instead of having multiple individual probots, I can combine them into one like so:

```json
{
  "name": "probot-combo-value-pack",
  "private": true,
  "dependencies": {
    "probot-stale": "probot/stale",
    "probot-settings": "probot/settings",
    "probot-autoresponder": "probot/autoresponder",
    "probot-autolabeler": "probot/autolabeler"
  },
  "scripts": {
    "start": "probot run"
  },
  "engines": {
    "node": "10.x"
  },
  "probot": {
    "apps": [
      "probot-stale",
      "probot-settings",
      "probot-autoresponder",
      "probot-autolabeler"
    ]
  }
}
```

Thanks a ton for your time. I appreciate it

**Comment by aegershman** [comment]
Turns out I was just accessing this wrong. Turns out you can just specify `probot/autoresponder`, *however* you have to reference the probot by it's name specified in `package.json`

Since the name for this project is actually [`probot-labeler`](https://github.com/probot/autolabeler/blob/master/package.json#L2), not `probot-AUTOlabeler`, I just had to reference it like that. 

E.g., this is what my `package.json` actually looks like now:

```json
{
  "name": "probot-combo-value-pack",
  "private": true,
  "dependencies": {
    "probot-stale": "probot/stale",
    "probot-settings": "probot/settings",
    "probot-autoresponder": "probot/autoresponder",
    "probot-labeler": "probot/autolabeler" # <--- must be referenced by the name in package.json
  },
  "scripts": {
    "start": "probot run"
  },
  "engines": {
    "node": "10.x"
  },
  "probot": {
    "apps": [
      "probot-stale",
      "probot-settings",
      "probot-autoresponder",
      "probot-labeler"  # <--- must be referenced by the name in package.json
    ]
  }
}
```

**Comment by mdelapenya** [comment]
There is an NPM package with same name: https://www.npmjs.com/package/probot-labeler
