### ISSUE TITLE
Tagging based on comment text

### ISSUE THREAD

**Issue by BenJWard** [probot/autolabeler#41]
Hi,

I'm looking for something like autolabeler to automate tagging for me, the tagging based on file can allow me to distinguish between say documentation changes and source changes, but I can't distinguish between a new feature and a bugfix.

I was wondering how useful or easy it would be to enable autolabeler to check the first comment in a PR, like this one: https://github.com/BioJulia/BioGenerics/pull/2, and then based in some of the tick boxes in there, update the tags.

**Comment by tunnckoCore** [comment]
Tags? You probably mean labels. 

But yea, sounds interesting.

**Comment by tunnckoCore** [comment]
Agree.
